### ISSUE TITLE
Running VMs DNS names vs. VMware Server Name

### ISSUE THREAD

**Issue by tiger12506** [tiger12506/VMAT#105] opened 2012-03-12 22:19 UTC
During this test, I also noticed that the 2 running VM’s had DNS names that did not match the VMAT page.  This makes sense, since the VMAT page displays the name stored in the VMware Server list.  Unfortunately, some of our engineers couldn’t care less about the VMware Server name.  9 times out of 10 they will be the same, but there have been a couple times we created a second VM and gave it the same DNS name for comparison testing.  Using the DNS name was my original intent, but I think the VMware Server name makes more things cleaner anyway – adding both would be a super low priority, they will deal with it.

**Comment by CalMlynarczyk** [comment] 2012-03-12 23:58
Duplicate of #86.

**Closed as completed by CalMlynarczyk** 2012-03-12 23:58 UTC
